version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pointcloud-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # root 用户的密码
      MYSQL_DATABASE: pointcloud_db    # 自动创建的数据库名
      MYSQL_USER: myuser               # 创建一个普通用户
      MYSQL_PASSWORD: myuser123       # 普通用户的密码
    ports:
      - "3307:3306"                    # MySQL 默认端口
    volumes:
      - ./mysql_data:/var/lib/mysql    # 数据持久化目录
    command: --default-authentication-plugin=mysql_native_password # 兼容性配置