version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pointcloud-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # Password for root user
      MYSQL_DATABASE: pointcloud_db # Automatically created database name
      MYSQL_USER: myuser # Create a user
      MYSQL_PASSWORD: myuser123 # User's password
    ports:
      - "3307:3306" # MySQL default port
    volumes:
      - ./mysql_data:/var/lib/mysql # Data Persistence Directory
    command: --default-authentication-plugin=mysql_native_password # Compatibility Configuration
